on: 
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE }}:latest
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            touch works.txt
            echo "Great, it works! at $(date)" >> works.txt
            sudo chmod 777 /var/run/docker.sock
            docker rmi ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE }}:latest
            docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE }}:latest
            docker stop ${{ secrets.CONTAINER }}
            docker rm ${{ secrets.CONTAINER }}
            docker run --name ${{ secrets.CONTAINER }} -e DBUSER=${{ secrets.DB_USER }} -e DBPASS=${{ secrets.DB_PASSWORD }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DBPORT }} -e DB_NAME=${{ secrets.DB_NAME }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} -e CLOUDINARY_CLOUD_NAME=${{ secret.sCLOUDINARY_CLOUD_NAME }} --link ${{ secrets.DB_HOST }} -d -p 80:8080 ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE }}
